### ISSUE TITLE
When "hide this category" was selected, the category did not disappear. 

### ISSUE THREAD

**Issue by hrvalli** [sakaiproject/sakai#2803] opened 2016-06-10 18:53 UTC
When I tested "hide this category" in https://qa11-mysql.nightly.sakaiproject.org/, the category was not hidden.

**Comment by kyleblythe** [comment] 2016-06-16 21:14
Hi @hrvalli ,

We're having some trouble reproducing this. Can you send a link to the site in which you were experiencing this issue? Can you also send along your browser/OS info?

**Comment by hrvalli** [comment] 2016-06-17 12:03
Hello.

I was testing on https://trunk-mysql.nightly.sakaiproject.org<https://trunk-mysql.nightly.sakaiproject.org/>, using a Mac (OS X 10.10.5) and Chrome (Version 51.0.2704.84 (64-bit))

Thanks,

Heather

**Comment by kyleblythe** [comment] 2016-06-23 21:41
Hi @hrvalli ,

We tried in trunk using the OS/browser combo you described, and weren't able to reproduce.

Is there a specific site in trunk-mysql that you were experiencing this in?

**Comment by hrvalli** [comment] 2016-06-24 14:44
There was, but I believe the sites get cleared regularly, so it's gone now. Sorry.

**Comment by kyleblythe** [comment] 2016-06-30 13:29
Hi @hrvalli ,

No worries! Since we weren't able to reproduce, I'm going to go ahead and close this issue for the time being. If you experience it again, please feel free to re-open, link to the site ID in question, and let us know the category that you're unable to hide.

Thanks!

**Closed by kyleblythe** 2016-06-30 13:29 UTC

**Comment by steveswinsburg** [comment] 2016-07-01 23:30
Also make sure your browser cache is reset. Sakai aggressively caches
static resources and it may just be that you had an old copy.

sent from my mobile
