### ISSUE TITLE
Gradebook manual grade entry triggers stacktrace

### ISSUE THREAD

**Issue by lgekeler** [sakaiproject/sakai#4215] opened 2017-04-06 17:25 UTC
I left it in jira before thinking: https://jira.sakaiproject.org/browse/SAK-32425

**Comment by steveswinsburg** [comment] 2017-04-07 23:51
this should be fixed in #3930  - the stacktrace in the above has:
`Caused by: java.lang.NumberFormatException: For input string: "6,5"`

**Closed** 2017-04-07 23:51 UTC
Labels: bug, GradebookNG
