### ISSUE TITLE
Add Gradebook Item - "Categories have not been configured" false error

### ISSUE THREAD

**Issue by lgekeler** [sakaiproject/sakai#2060] opened 2016-03-30 17:47 UTC
http://www.screencast.com/t/bpBdCHMyJ

1. Display error (morpheus)
2. Categories were intentionally not configured yet a false error conditions displays, "Items not assigned to a category will not be counted toward the course grade calculation." Settings are these: http://www.screencast.com/t/2gRtOoMj

Testing on trunk-mysql.nightly (as in screen cap, on date in screen cap).

**Comment by kyleblythe** [comment] 2016-03-30 18:03
Additional info:

1. This issue, wherein the datepicker icons aren't appearing, might have to do with the other empty buttons that we've noted in #1858 .

2. This is a great catch. We'll want to remove this blue info box from the "Add Gradebook Item" lightbox window when categories haven't been enabled in the GB.

Thanks for these, @lgekeler !

**Comment by steveswinsburg** [comment] 2016-03-31 10:09
This was intentional, but it can be adjusted. Should the category section not show at all?

**Comment by kyleblythe** [comment] 2016-03-31 18:43
I think that we can keep the category section, with the current text that replaces the dropdown saying "Categories have not been configured."

However, I think we can remove this blue info box when the GB is set to "No categories": 

![image](https://cloud.githubusercontent.com/assets/11447474/14186977/ece908da-f74e-11e5-951d-9df8fc5cef83.png)

This info field is suggesting that nothing will be included in course grade calculations, since there aren't categories. However, that's not the case when it's set to "No categories"

**Comment by lgekeler** [comment] 2016-03-31 18:57
Even the "Categories have not been configured" implies to me that I did
something wrong.

I think keeping it is a bad idea.

Laura Gekeler
LMS Administrator
Teaching and Learning Technologies
Apereo Foundation <https://www.apereo.org/content/projects-communities>
Board '14-2017
University of Notre Dame
Sakai_Team-group@nd.edu

**Comment by kyleblythe** [comment] 2016-04-05 15:13
Confirmed!

![image](https://cloud.githubusercontent.com/assets/11447474/14287093/7bf73dfc-fb1f-11e5-8187-14c8e43a4b36.png)

**Closed by kyleblythe** 2016-04-05 15:13 UTC
Labels: bug, GradebookNG, ready to test
