### ISSUE TITLE
Can't enter grades using the 'numeric keypad' - desktop keyboards

### ISSUE THREAD

**Issue by jmarianolujan** [sakaiproject/sakai#1775] opened 2016-02-23 13:45 UTC
When using a desktop computer, a user can't enter grades (GBNG spreadsheet entry mode) using the numbers from the 'numeric keypad' (right side of the keyboard).

Steps to reproduce it:

   1- clic on the first empty grade cell, first student on the list
   2- clic 'enter' or 'down arrow' to move down to the next student
   3- try to enter the next grade by using the numeric keypad (you can't). You can if you use the numbers from the top row of the keyboard (not from the numeric keypad).

   If you clic on the next cell instead of trying to enter the grade directly with the keypad number, then the focus is activated and you will be able to enter grades with the keypad numbers.

**Comment by juanjmerono** [comment] 2016-02-23 15:13
I think the problem is in this line:
https://github.com/sakaiproject/sakai/blob/master/gradebookng/tool/src/webapp/scripts/gradebook-grades.js#L150

```
} else if (isEditableCell && event.keyCode >= 48 && event.keyCode <= 57) {
```

It should include the key codes for numeric pad:
```
} else if (isEditableCell && ((event.keyCode >= 48 && event.keyCode <= 57) || (e.keyCode >= 96 && e.keyCode <= 105))) {
```
And also change the management of the codes in this line:
https://github.com/sakaiproject/sakai/blob/master/gradebookng/tool/src/webapp/scripts/gradebook-grades.js#L1677

Adding the handle for those key codes:
```
if (keyCode >= 96 && keyCode <= 105) {
      initialValue = keyCode - 96;
}
```

**Comment by jonespm** [comment] 2016-02-23 15:21
Thanks for the detail. It looks like hitting a numeric key by itself activates focus. This description makes sense and I was actually testing it by hitting "enter" and typing numbers which was working fine. :)

Good site to test codes http://www.asquare.net/javascript/tests/KeyCode.html

**Comment by steveswinsburg** [comment] 2016-02-29 11:58
This is merged. @jmarianolujan could you please verify? If you can't close this ticket, let me know and I will. Cheers.

**Comment by jmarianolujan** [comment] 2016-02-29 13:25
Hey @steveswinsburg, its NOT working as expected, but... good news, it seems to be an easy fix, I just saw @juanjmerono's comment in #1812

**Comment by steveswinsburg** [comment] 2016-03-03 20:09
Hey guys, thanks for the testing. Just letting you know that we are happy to accept a pull request against this project if you already have the code snippet ready to go. We were following the code snippet that @juanjmerono posted above and don't actually have a keypad to test this out fully. @payten is onto the fix for this :+1:

**Comment by steveswinsburg** [comment] 2016-03-03 20:46
Thanks @payten, new fix is in, @jmarianolujan could you please verify?

**Comment by jmarianolujan** [comment] 2016-03-04 11:50
Thanks! on a laptop right now, I'll check on monday and let you know as soon as I get back to the office. I'll let you know!

**Comment by jmarianolujan** [comment] 2016-03-07 07:43
This is now working as expected! Thanks guys!

**Closed** 2016-03-07 09:46 UTC
Labels: bug, GradebookNG, ready to test
