### ISSUE TITLE
Weight shouldn't appear in student view with categories only

### ISSUE THREAD

**Issue by jonespm** [sakaiproject/sakai#3603] opened 2016-11-17 20:40 UTC
If you select "Categories Only" in the setting (without Weight) and you view as a student in the class it shows a Weight of 0%. This is confusing to some students. It shouldn't show any weight if it's not using weighted categories. Tested this on 11.x

To test, create an assessment as "Categories only" and add a category. Add a gradebook item to it. Login as a student in the class, there shouldn't be anything there for the "Weight" 

![image](https://cloud.githubusercontent.com/assets/27447/20406608/3091d6c0-accb-11e6-9db1-ff17be70c7be.png)

**Comment by kyleblythe** [comment] 2016-11-21 13:34
Hi @payten ,

Weird - I thought we'd already addressed this before w/ the grade summary lightbox, [but the weight appears to be showing up there too](http://www.screencast.com/t/c6i6Lh5ieHM7). Would #3611 address the weight column showing up in both the student view and the grade summary/student review mode lightboxes?

Thanks!

**Comment by payten** [comment] 2016-11-21 19:07
Yeah! I thought we'd done this, but seems to be a regression.. programming is hard 😢

The patch above should fix both views, but let's give it a good test once the PR is merged!

**Comment by kyleblythe** [comment] 2016-12-01 21:01
Confimed: http://www.screencast.com/t/ss7zrywb77U

**Closed by kyleblythe** 2016-12-01 21:01 UTC
Labels: bug, GradebookNG, ready to test

**Comment by ncaidin** [comment] 2017-05-18 15:05
Tested and verified on nightly 11.x Mysql Server. (should I add a label?)
