### ISSUE TITLE
GradebookNG doesn't duplicate items when duplicating a site.

### ISSUE THREAD

**Issue by willkara** [sakaiproject/sakai#1587] opened 2016-01-19 18:24 UTC
Had one of our students try it on our instance of Sakai 11 and the communities.

GradebookNG items did not copy over when I tried to duplicate the site.

**Comment by jonespm** [comment] 2016-01-19 23:27
Looks related, not in the edu-services code. Only in gradebook
https://jira.sakaiproject.org/browse/SAK-7583

**Comment by steveswinsburg** [comment] 2016-01-24 11:10
There are likely two causes to this:
1. Is that the existing GradebookEntityProducer lists sakai.gradebook.tool as the only toolId, and GradebookNg is sakai.gradebookng.
2. is that we do also have our own EntityProducer that allows for the bootstrapping of the tool into new sites, so it is trivial to update this as the actual code is in the GradebookService.

However, weird things would happen if you had both Gradebook and GradebookNG in the site and tried to duplicate the site with both tools selected. At the least we might get duplicate items, however we would more likely get errors due to the gradebook item name being already in use in the site.

So before I fix this we need to decide what the behaviour is.
If Gradebook classique is merged first, then the GradebookNG entityproducer could just check if the items exist in the new site and skip them.

Thoughts?

**Comment by steveswinsburg** [comment] 2016-02-14 13:52
This is pretty much done, just doing some final testing.

**Comment by steveswinsburg** [comment] 2016-02-15 10:26
Scenarios tested:

Create a site, siteA, with custom grading schema, assignments in categories, assignments with out categories and categories without assignments.

1. Created new site, siteB, select GradebookNG as the tool, reuse content from siteA. Custom grading schema, categories and assignments come across fine.
2. Created new site, siteC. After creation chose to import from siteA and replace data. Selected GradebookNG tool to import from. Custom grading schema, categories and assignments come across fine.
3. In siteC, chose to import from siteA and merge data, even though it already existed. Process checks if items exist and gracefully skips them. This is an improvement over and above the old import which threw exceptions.
4. Created new site, siteD. After creation chose to import from siteA and replace data. Selected Gradebook and GradebookNG tools to import from. Custom grading schema, categories and assignments come across fine. Process goes ahead but skips everything gracefully.
5. In siteD, chose to import from siteA and merge data, even though it already existed. Process goes ahead but skips everything gracefully.

**Comment by kyleblythe** [comment] 2016-02-18 18:25
Confirmed.

**Closed by kyleblythe** 2016-02-18 18:25 UTC
Labels: BLOCKER, bug, GradebookNG, priority, ready to test
