### ISSUE TITLE
Error page when opening gradebook IllegalArgumentException

### ISSUE THREAD

**Issue by jonespm** [sakaiproject/sakai#3246] opened 2016-08-23 04:18 UTC
We're seeing this full page stack trace on a few sites on a converted instance when first visiting Gradebook NG.

My best guess is that score in 
return formatGrade(df.format(score));

is not being NPE checked correctly. This code "probably" should be
df.format(score == null ? 0.0 : score);

Unless you wanted to just return null. I'm not sure yet why it's null in the first place though.

```
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Number
 at java.text.DecimalFormat.format(DecimalFormat.java:507)
 at java.text.Format.format(Format.java:157)
 at org.sakaiproject.gradebookng.business.util.FormatHelper.formatDoubleToTwoDecimalPlaces(FormatHelper.java:30)
```

**Comment by payten** [comment] 2016-08-23 05:30
Thanks @jonespm, there's a few places that call `formatDoubleToTwoDecimalPlaces` when the tool first loads (when showing assignment scores, course grades, category averages and category weights).  Do you happen to have the full stack trace handy?

**Comment by jonespm** [comment] 2016-08-23 05:33
Yeah it's gigantic, but here it is!

```
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor 'public org.sakaiproject.gradebookng.tool.pages.GradebookPage()'. An exception has been thrown during construction!
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:194)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:67)
	at org.apache.wicket.DefaultMapperContext.newPageInstance(DefaultMapperContext.java:133)
	at org.apache.wicket.core.request.handler.PageProvider.resolvePageInstance(PageProvider.java:268)
	at org.apache.wicket.core.request.handler.PageProvider.getPageInstance(PageProvider.java:166)
	at org.apache.wicket.request.handler.render.PageRenderer.getPage(PageRenderer.java:78)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:117)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:229)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:406)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1459)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doToolBuffer(SiteHandler.java:1154)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent(SiteHandler.java:1010)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:484)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:263)
	at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:151)
	at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:835)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:467)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor706.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:175)
	... 61 more
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Number
	at java.text.DecimalFormat.format(DecimalFormat.java:507)
	at java.text.Format.format(Format.java:157)
	at org.sakaiproject.gradebookng.business.util.FormatHelper.formatDoubleToTwoDecimalPlaces(FormatHelper.java:30)
	at org.sakaiproject.gradebookng.business.util.FormatHelper.formatDoubleAsPercentage(FormatHelper.java:41)
	at org.sakaiproject.gradebookng.business.util.CourseGradeFormatter.build(CourseGradeFormatter.java:130)
	at org.sakaiproject.gradebookng.business.util.CourseGradeFormatter.format(CourseGradeFormatter.java:76)
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:649)
	at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:563)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
	at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$ad7ec9a4.buildGradeMatrix(<generated>)
	at org.sakaiproject.gradebookng.tool.pages.GradebookPage.<init>(GradebookPage.java:212)
	... 65 more
```

**Comment by payten** [comment] 2016-08-23 05:39
Awesome ;)  Thanks @jonespm.  Looks like something is amiss rendering the course grade, stemming from this line:
```
		if (this.showOverride && StringUtils.isNotBlank(courseGrade.getEnteredGrade())) {
			calculatedGrade = FormatHelper.formatDoubleAsPercentage(
				gradebook.getSelectedGradeMapping().getGradeMap().get(courseGrade.getEnteredGrade()));
```

A `null` value here might imply that the grade override provided by the instructor doesn't map to a grade within the letter grade mapping schema.  I think we assumed that all override values would match up.  Do you have a scenario when this wouldn't be the case?

**Comment by payten** [comment] 2016-08-23 05:48
I can confirm the bug - if I thinker the database and set a course override to non-mapped value e.g. 'Z', I get the exact stack trace above. You can't enter a non-mapped grade in "Gradebook Classic" as far as I can tell (???) - do you know how to best replicate this scenario?  Thanks!

**Comment by jonespm** [comment] 2016-08-23 06:47
Thanks @payten you're right. It looks like this client had a  lot of custom modification to the original gradebook that allowed for custom letter grades that all mapped to 0.0. So gradebook NG can't deal with them. 

I think it would be *nice* if Gradebook NG did map an unknown value to 0 that would solve this problem but we'll probably have to re-work this anyway. Thanks for the information!

**Comment by jonespm** [comment] 2016-08-23 06:53
I might wait on this if a simple fix doesn't get this anywhere. Because even if it works and doesn't return an error, it seems like we're going to have to provide some type of type of support for entry of custom grades that don't exist in the regular mapping.

**Comment by payten** [comment] 2016-08-23 07:19
@jonespm, to keep things working it makes sense to me to map any unknown overrides to 0.0.  Perhaps we can do that and also log a warning.

**Comment by steveswinsburg** [comment] 2016-08-23 10:41
Yep this should be a bit easier on the conversion. I'll fix this tonight.

**Comment by steveswinsburg** [comment] 2016-08-23 11:52
Ok this is fixed in #3246. 

However I think this needs a bit of thought as to how to handle it even better. If you override a student's course grade to A+ and then change the Grading Schema to be Letter Grades only, their course grade shows as A+ (0%) because A+  can't be mapped.

It would be simple to present a warning to the instructor if they are changing the grading schema and if course grades are using the current schema that they will need to be updated. @kyleblythe , thoughts on this?

I don't recommend automatically remapping them to the new schema due to the risk, but a warning would be 👌 .

**Comment by payten** [comment] 2016-08-23 23:30
Hi @jonespm, a patch has been merged.  It'd be great if you can confirm this fixes things for you.

Perhaps we can add another enhancement task for a patch to ensure the data cannot be easily put into this state or at least the instructor is notified of overridden grades that no longer map?

**Comment by steveswinsburg** [comment] 2016-08-24 10:59
Yep I think we'll discuss with @kyleblythe on the course of action here. Thanks for spotting this one.

**Comment by kyleblythe** [comment] 2016-08-24 13:43
Thanks @jonespm , @payten and @steveswinsburg !

I've created #3258 for this enhancement.

**Comment by kyleblythe** [comment] 2016-09-01 20:14
Confirmed. 

![image](https://cloud.githubusercontent.com/assets/11447474/18182722/26fd3058-705f-11e6-994f-801ead836733.png)

**Closed by kyleblythe** 2016-09-01 20:14 UTC
Labels: bug, GradebookNG, ready to test
