### ISSUE TITLE
With percentages on, editing Gradebook item changes all existing grades

### ISSUE THREAD

**Issue by payten** [sakaiproject/sakai#3210] opened 2016-08-18 02:34 UTC
To replicate:
1. Have a Gradebook with percentages enabled
2. Have a Gradebook item with grades
<img width="581" alt="screen shot 2016-08-18 at 12 32 13 pm" src="https://cloud.githubusercontent.com/assets/608337/17760050/e8ecebac-653f-11e6-8339-b770dc59b95c.png">
3. "Edit Item Details" and click Save (you don't have to actually change anything)
4. Grades all different:
<img width="604" alt="screen shot 2016-08-18 at 12 32 25 pm" src="https://cloud.githubusercontent.com/assets/608337/17760065/05fe7792-6540-11e6-95f0-dc404c95596d.png">
5. "Edit Item Details" again...
6. Grades different again:
<img width="584" alt="screen shot 2016-08-18 at 12 32 36 pm" src="https://cloud.githubusercontent.com/assets/608337/17760068/129b257c-6540-11e6-86d6-5adc6b6bbf4c.png">

**Comment by payten** [comment] 2016-08-18 03:57
@steveswinsburg, the comparison around `scaleGrades` seems to be the culprit? : https://github.com/sakaiproject/sakai/blob/master/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java#L814

**Comment by steveswinsburg** [comment] 2016-08-18 12:21
Oh, yes that does look like a problem as it will be doing a Double object comparison instead of a primitive value comparison. However we'll want: 
`!assignment.getPointsPossible().compareTo(assignmentDefinition.getPoints())`

I'll try to fix this tonight.

**Comment by steveswinsburg** [comment] 2016-08-18 12:50
Ok PR here. Good catch.

Might need to check on the behaviour with the scale grades to ensure it's correct. I'm seeing something odd.

*Consider this scenario:*
1. If I have a relative item weight of 100 and give a grade of 10%, in the db they get 10 points.
2. If I change that relative item weight to 50, the grade stays as 10%, but in the db it is converted to 5 points (as 5/50 = 10%)
3. If I change that relative item weight to 100, the grade goes to 5% and in the db it stays as 5 points.
4. If I change that relative item weight to 200, the grade stays at 5%  but in the db it is converted to 10 points.

So strangely, in case 3, the points aren't being scaled. Do you see something similar?

**Comment by payten** [comment] 2016-08-18 23:28
Hi @steveswinsburg, I can confirm that the scenario you described above is indeed a bug.  It seems the code here is assuming the value is a percentage: https://github.com/sakaiproject/sakai/blob/master/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java#L1399
```
    protected Double calculateEquivalentPointValueForPercent(Double doublePointsPossible, Double doublePercentEarned) {
      ...
	BigDecimal pointsPossible = new BigDecimal(doublePointsPossible.toString());
		BigDecimal percentEarned = new BigDecimal(doublePercentEarned.toString());
		BigDecimal equivPoints = pointsPossible.multiply(percentEarned.divide(new BigDecimal("100"), GradebookService.MATH_CONTEXT));
		return Double.valueOf(equivPoints.doubleValue());
    }
```

However, it is called with the grade's raw point value: https://github.com/sakaiproject/sakai/blob/master/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java#L3660
```
...
gradeRecords.forEach(gr -> gr.setPointsEarned(
	calculateEquivalentPointValueForPercent(assignment.getPointsPossible(), gr.getPointsEarned())));
...
```

I think the fix will resolve around converting that gr.getPointsEarned() to a percentage based on the assignments original "points possible" value?

**Comment by steveswinsburg** [comment] 2016-08-22 10:13
OK sweet send a PR and I'll check it out :)

**Comment by kyleblythe** [comment] 2016-08-23 17:59
Confirmed.

**Comment by payten** [comment] 2016-09-15 01:53
Reopening this issue because I think the patch is potentially creating invalid scores.   I think we need to adjust this line to restrict the score to two decimal places - currently it could generate a double with any number of decimal places:

https://github.com/sakaiproject/sakai/pull/3243/files#diff-384199da4cecb79cddce096ef63439c7R3668

My concern is that by shortening the score we then lose the accuracy of the percentage score. For example, if an assignment is out of 10 and we give a score 30.35%, which is currently saved as 3.035 in the database.  If we change to points, then is now invalid.  If we try to update the value, it converts to two decimal places and throws a concurrent edit error because it doesn't match up.  And if we were to truncate to 2 decimal places before we save, then score would become 3.04 and then show up as 30.4% when the user reloads the page. 

It's a quandary!  Any ideas? @steveswinsburg @kyleblythe @jeffpasch

**Comment by steveswinsburg** [comment] 2016-09-22 21:22
Since this has been partially merged to 11.x I've added the blocker label so the rest can be done before 11.2.

**Comment by steveswinsburg** [comment] 2016-10-06 20:11
PR from #3349 has been refactored and merged. This completes this issue and should go to 11.x (11.2)

**Comment by kyleblythe** [comment] 2016-10-11 16:55
Confirmed in trunk:

![2016-10-11_12-46-11-1](https://cloud.githubusercontent.com/assets/11447474/19280014/e7abbc0e-8fb1-11e6-8194-c786f6a9b610.gif)

**Closed by kyleblythe** 2016-10-11 16:55 UTC
Labels: BLOCKER, bug, GradebookNG, ready to test
